#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a '*' state=floating

nitrogen --restore &
udiskie -Ant &
xrandr --output Virtual-1 --mode 1920x1080 &
picom &
conky -c ~/.conkyrc &
polybar &
sxhkd &

